# Generated by Django 4.0.1 on 2022-05-14 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('video', models.URLField()),
                ('reyting', models.FloatField(default=0)),
                ('reyting_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='age',
        ),
        migrations.RemoveField(
            model_name='client',
            name='avarage',
        ),
        migrations.RemoveField(
            model_name='client',
            name='days',
        ),
        migrations.RemoveField(
            model_name='client',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='client',
            name='height',
        ),
        migrations.RemoveField(
            model_name='client',
            name='register_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='task_dieta_can_not',
        ),
        migrations.RemoveField(
            model_name='client',
            name='task_sport_can_not',
        ),
        migrations.RemoveField(
            model_name='client',
            name='task_type',
        ),
        migrations.RemoveField(
            model_name='client',
            name='week_result',
        ),
        migrations.RemoveField(
            model_name='client',
            name='weight',
        ),
        migrations.AddField(
            model_name='client',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'client'), (2, 'expert')], default=1),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[(1, 'Erkak'), (2, 'Ayol')], max_length=30)),
                ('register_date', models.DateField()),
                ('week_result', models.IntegerField()),
                ('avarage', models.IntegerField(default=0)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('task_type', models.CharField(choices=[(1, 'Dieta'), (2, 'Sport'), (3, 'All')], max_length=30)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('days', models.ManyToManyField(to='API.Day')),
                ('task_dieta_can_not', models.ManyToManyField(related_name='NoDieta', to='API.Sport')),
                ('task_sport_can_not', models.ManyToManyField(to='API.Sport')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryReyting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField()),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.expert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.user')),
            ],
        ),
        migrations.AddField(
            model_name='expert',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
