# Generated by Django 4.0.4 on 2022-05-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
