# Generated by Django 4.0.1 on 2022-05-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_expert_remove_client_age_remove_client_avarage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='days',
        ),
        migrations.AlterField(
            model_name='expert',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Erkak'), (2, 'Ayol')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='task_type',
            field=models.IntegerField(choices=[(1, 'Dieta'), (2, 'Sport'), (3, 'All')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='week_result',
            field=models.IntegerField(default=0),
        ),
    ]
