# Generated by Django 4.0.4 on 2022-05-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_client_age_alter_client_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='task_all',
            field=models.ManyToManyField(to='API.taskall'),
        ),
        migrations.AlterField(
            model_name='client',
            name='task_dieta',
            field=models.ManyToManyField(to='API.taskdieta'),
        ),
        migrations.AlterField(
            model_name='client',
            name='task_dieta_can_not',
            field=models.ManyToManyField(related_name='NoDieta', to='API.sport'),
        ),
        migrations.AlterField(
            model_name='client',
            name='task_sport',
            field=models.ManyToManyField(to='API.tasksport'),
        ),
        migrations.AlterField(
            model_name='client',
            name='task_sport_can_not',
            field=models.ManyToManyField(to='API.sport'),
        ),
    ]
