# Generated by Django 4.0.4 on 2022-05-14 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_client_task_all_alter_client_task_dieta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='task_all',
        ),
        migrations.RemoveField(
            model_name='client',
            name='task_dieta',
        ),
        migrations.RemoveField(
            model_name='client',
            name='task_sport',
        ),
        migrations.AddField(
            model_name='client',
            name='avarage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='task_type',
            field=models.CharField(choices=[(1, 'Dieta'), (2, 'Sport'), (3, 'All')], default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='week_result',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskdieta',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskdieta',
            name='limit',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskdieta',
            name='lunch',
            field=models.ManyToManyField(related_name='lunch_time', to='API.product'),
        ),
        migrations.AddField(
            model_name='taskdieta',
            name='morning',
            field=models.ManyToManyField(related_name='morning_time', to='API.product'),
        ),
        migrations.AddField(
            model_name='taskdieta',
            name='night',
            field=models.ManyToManyField(to='API.product'),
        ),
        migrations.AddField(
            model_name='tasksport',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='API.sport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasksport',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasksport',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TaskAll',
        ),
        migrations.AddField(
            model_name='client',
            name='days',
            field=models.ManyToManyField(to='API.day'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='API.categoryproduct'),
            preserve_default=False,
        ),
    ]
