# Generated by Django 4.0.4 on 2022-05-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_advice_categoryproduct_day_remove_client_task_all_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='register_date',
            field=models.DateField(),
        ),
    ]
